server:
  port: 6866
management:
  metrics:
    web:
      server:
        auto-time-requests: false
spring:
  application:
    name: zipcenter
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/c568254965/spring-cloud-config.git
        # git: https://github.com/c568254965/spring-cloud-config.git
zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      cluster: es-from-csrr
      hosts: http://locahlhost:9200
      index: csrr-zipkin
      index-shards: 5
      index-replicas: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:6801/eureka/
  instance:
    instance-id: huarui_zipkin   #自定义服务名称信息
    prefer-ip-address: true     #访问路径可以显示IP地址
#turbine:
#  app-config: huaruiuser,huaruidishes
#  cluster-name-expression: "'default'"


---
spring:
  profiles: test

zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      cluster: es-from-csrr
      hosts: http://140.143.227.51:9200
      index: csrr-zipkin
      index-shards: 5
      index-replicas: 1

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://140.143.227.51:6801/eureka/
  instance:
    instance-id: huarui_zipkin   #自定义服务名称信息
    prefer-ip-address: true #访问路径可以显示IP地址

zuul:
  routes:
    HUARUIDISHES: /dish/**
    HUARUI_USER: /user/**

#turbine:
#  app-config: huaruiuser
#  cluster-name-expression: "'default'"

