server:
  port: 6866
management:
  metrics:
    web:
      server:
        auto-time-requests: false
spring:
  profiles:
    active: dev
  cloud:
    config:
      server:
        git:
          uri: https://github.com/c568254965/spring-cloud-config.git
        # git: https://github.com/c568254965/spring-cloud-config.git

zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      cluster: es-from-csrr
      hosts: http://locahlhost:9200
      index: csrr-zipkin
      index-shards: 5
      index-replicas: 1

---
spring:
  profiles: test

zipkin:
  storage:
    StorageComponent: elasticsearch
    type: elasticsearch
    elasticsearch:
      cluster: es-from-csrr
      hosts: http://140.143.227.51:9200
      index: csrr-zipkin
      index-shards: 5
      index-replicas: 1